import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";

const foodImages={noodle:"https://images.unsplash.com/photo-1569718212165-3a8278d5f624?q=60&w=650&auto=format&fit=crop",curry:"https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?q=60&w=650&auto=format&fit=crop",rice:"https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=60&w=650&auto=format&fit=crop",thai:"https://images.unsplash.com/photo-1559847844-5315695dadae?q=60&w=650&auto=format&fit=crop",soup:"https://images.unsplash.com/photo-1547592166-23ac45744acd?q=60&w=650&auto=format&fit=crop",fried:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?q=60&w=650&auto=format&fit=crop",seafood:"https://images.unsplash.com/photo-1559737558-2f5a35f4523b?q=60&w=650&auto=format&fit=crop",drink:"https://images.unsplash.com/photo-1544145945-f90425340c7e?q=60&w=650&auto=format&fit=crop"};
const allMenus=[
{category:"ก๋วยเตี๋ยวเรือ",name:"ก๋วยเตี๋ยวเรือหมูน้ำตก",desc:"น้ำซุปเข้มข้น หอมเครื่องเทศ หมูนุ่ม ลูกชิ้นแน่น",price:"40.-",image:foodImages.noodle},{category:"ก๋วยเตี๋ยวเรือ",name:"ก๋วยเตี๋ยวเรือเนื้อน้ำตก",desc:"เนื้อนุ่ม น้ำตกเข้มข้น รสจัดจ้าน",price:"50.-",image:foodImages.noodle},{category:"ก๋วยเตี๋ยวเรือ",name:"ก๋วยเตี๋ยวเรือหมูพิเศษ",desc:"เครื่องแน่น หมูสด หมูตุ๋น ลูกชิ้น",price:"55.-",image:foodImages.noodle},{category:"ก๋วยเตี๋ยวเรือ",name:"เกาเหลาหมูน้ำตก",desc:"เกาเหลาเครื่องหมูแน่น น้ำซุปเข้ม",price:"60.-",image:foodImages.soup},{category:"ก๋วยเตี๋ยวเรือ",name:"แคบหมู",desc:"กรอบ หอม ทานคู่ก๋วยเตี๋ยวเรือ",price:"15.-",image:foodImages.fried},
{category:"ขนมจีน",name:"ขนมจีนน้ำยากะทิ",desc:"น้ำยากะทิหอมมัน เครื่องแกงถึงรส",price:"45.-",image:foodImages.curry},{category:"ขนมจีน",name:"ขนมจีนน้ำยาป่า",desc:"รสจัดจ้าน หอมสมุนไพร ไม่ใส่กะทิ",price:"45.-",image:foodImages.curry},{category:"ขนมจีน",name:"ขนมจีนแกงเขียวหวานไก่",desc:"แกงเขียวหวานเข้มข้น ไก่นุ่ม หอมกะทิ",price:"55.-",image:foodImages.curry},{category:"ขนมจีน",name:"ขนมจีนน้ำยาปู",desc:"เนื้อปูหอมมัน น้ำยาเข้มข้น",price:"75.-",image:foodImages.seafood},
{category:"ข้าวกะเพรา",name:"กะเพราหมูสับราดข้าว",desc:"ผัดไฟแรง หอมกะเพราแท้",price:"50.-",image:foodImages.rice},{category:"ข้าวกะเพรา",name:"กะเพราไก่ราดข้าว",desc:"ไก่นุ่ม ผัดแห้ง หอมเผ็ดกำลังดี",price:"50.-",image:foodImages.rice},{category:"ข้าวกะเพรา",name:"กะเพราเนื้อราดข้าว",desc:"เนื้อหอม ผัดจัดจ้านถึงเครื่อง",price:"65.-",image:foodImages.rice},{category:"ข้าวกะเพรา",name:"กะเพราหมูกรอบราดข้าว",desc:"หมูกรอบแน่น ผัดกะเพราเข้มข้น",price:"65.-",image:foodImages.rice},{category:"ข้าวกะเพรา",name:"กะเพราทะเลราดข้าว",desc:"กุ้ง หมึก สดใหม่ ผัดไฟแรง",price:"75.-",image:foodImages.seafood},{category:"ข้าวกะเพรา",name:"เพิ่มไข่ดาว",desc:"ไข่ดาวกรอบนอก ไข่แดงเยิ้ม",price:"10.-",image:foodImages.fried},
{category:"กับข้าว",name:"ต้มยำรวมมิตร",desc:"กุ้ง หมึก หมู ไก่ น้ำต้มยำแซ่บ",price:"120.-",image:foodImages.soup},{category:"กับข้าว",name:"แกงจืดเต้าหู้หมูสับ",desc:"น้ำซุปใส หอมหวาน ทานง่าย",price:"90.-",image:foodImages.soup},{category:"กับข้าว",name:"ยำวุ้นเส้นทะเล",desc:"ยำรสแซ่บ กุ้งหมึกสด",price:"120.-",image:foodImages.seafood},{category:"กับข้าว",name:"ปีกไก่ทอด",desc:"ทอดกรอบนอก นุ่มใน",price:"90.-",image:foodImages.fried},
{category:"เครื่องดื่ม",name:"น้ำเปล่า",desc:"น้ำดื่มเย็นสดชื่น",price:"10.-",image:foodImages.drink},{category:"เครื่องดื่ม",name:"ชาไทยเย็น",desc:"ชาไทยหอมมัน หวานกำลังดี",price:"35.-",image:foodImages.drink},{category:"เครื่องดื่ม",name:"ชาเขียวเย็น",desc:"ชาเขียวหอมละมุน สดชื่น",price:"35.-",image:foodImages.drink}];
function priceNumber(price){return Number(String(price).replace(/[^0-9]/g,"")||0)}
function lineLink(text){return `https://line.me/R/share?text=${encodeURIComponent(text)}`}
function Btn({children,onClick,style={},outline=false}){return <button onClick={onClick} className="btn" style={{border:outline?"1px solid rgba(255,255,255,.35)":0,background:outline?"rgba(255,255,255,.08)":"#8B4513",...style}}>{children}</button>}
function App(){
const isAdminMode=typeof window!=="undefined"&&window.location.search.includes("admin=1");
const [adminLoggedIn,setAdminLoggedIn]=useState(false);const [adminPassword,setAdminPassword]=useState("");const adminOpen=isAdminMode&&adminLoggedIn;
const [selectedCategory,setSelectedCategory]=useState("ทั้งหมด");const [adminCategory,setAdminCategory]=useState("ทั้งหมด");const [menus,setMenus]=useState(allMenus);const [cart,setCart]=useState([]);const [customer,setCustomer]=useState({name:"",phone:"",address:"",spicy:"เผ็ดกลาง",note:""});const [orderType,setOrderType]=useState("รับเอง");const [newMenu,setNewMenu]=useState({category:"",name:"",price:"",desc:"",image:""});
const [site,setSite]=useState({shopName:"บ้านอิ่มสุข",slogan:"อาหารไทยรสพรีเมียม อิ่มอร่อยทุกมื้อ",headline:"บ้านอิ่มสุข สุรินทร์",highlight:"ก๋วยเตี๋ยวเรือ ขนมจีน กะเพรา ปราสาท",intro:"ร้านบ้านอิ่มสุข อำเภอปราสาท จังหวัดสุรินทร์ ก๋วยเตี๋ยวเรือ ขนมจีน และกะเพรา อร่อยเข้มข้น วัตถุดิบสดใหม่ เปิดทุกวัน พร้อมสั่งกลับบ้านและเดลิเวอรี่",phone:"0xx-xxx-xxxx",line:"@imsuk",address:"ร้านบ้านอิ่มสุข อำเภอปราสาท จังหวัดสุรินทร์",mapEmbedUrl:"https://www.google.com/maps?q=ปราสาท%20สุรินทร์&output=embed",mainColor:"#8B4513",accentColor:"#D4AF37",openTime:"08:00 - 20:00",deliveryFee:"20",shopStatus:"เปิดอยู่",bestseller1:"ก๋วยเตี๋ยวเรือหมูน้ำตก",bestseller2:"ขนมจีนน้ำยากะทิ",bestseller3:"กะเพราหมูกรอบราดข้าว",bestsellerCount:"120+",review1:"ก๋วยเตี๋ยวเรือน้ำเข้มข้น อร่อยมากค่ะ",review2:"ขนมจีนสด น้ำยาหอมมัน ให้เยอะ คุ้มราคา",review3:"กะเพราหมูกรอบเด็ดมาก สั่งซ้ำแน่นอน",heroImages:["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?q=65&w=850&auto=format&fit=crop","https://images.unsplash.com/photo-1544025162-d76694265947?q=65&w=850&auto=format&fit=crop","https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=65&w=850&auto=format&fit=crop"]});
const categories=["ทั้งหมด",...Array.from(new Set(menus.map(m=>m.category)))];const visibleMenus=selectedCategory==="ทั้งหมด"?menus:menus.filter(m=>m.category===selectedCategory);const adminMenus=adminCategory==="ทั้งหมด"?menus.map((item,index)=>({item,index})):menus.map((item,index)=>({item,index})).filter(({item})=>item.category===adminCategory);const bestsellerNames=[site.bestseller1,site.bestseller2,site.bestseller3];
const cartTotal=cart.reduce((s,i)=>s+priceNumber(i.price)*i.qty,0);const deliveryFee=orderType==="จัดส่ง"?priceNumber(site.deliveryFee):0;const grandTotal=cartTotal+deliveryFee;const totalQty=cart.reduce((s,i)=>s+i.qty,0);
const cartText=cart.length?[`สวัสดีครับ ร้าน${site.shopName}`,"ผมต้องการสั่งอาหาร:",...cart.map((item,i)=>`${i+1}. ${item.name} x${item.qty} = ${priceNumber(item.price)*item.qty} บาท`),`ค่าอาหาร ${cartTotal} บาท`,`ค่าจัดส่ง ${deliveryFee} บาท`,`ยอดสุทธิ ${grandTotal} บาท`,`รูปแบบ: ${orderType}`,`ชื่อผู้สั่ง: ${customer.name||"-"}`,`เบอร์โทร: ${customer.phone||"-"}`,`ระดับความเผ็ด: ${customer.spicy}`,`หมายเหตุ: ${customer.note||"-"}`,`ที่อยู่/รับเอง: ${orderType==="จัดส่ง"?customer.address||"-":"รับเองที่ร้าน"}`].join("\n"):`สวัสดีครับ ร้าน${site.shopName} ผมต้องการสั่งอาหารครับ`;
const updateSite=(key,value)=>setSite({...site,[key]:value});const updateMenu=(index,key,value)=>{const next=[...menus];next[index]={...next[index],[key]:value};setMenus(next)};const addToCart=(item)=>{const found=cart.find(x=>x.name===item.name);if(found)setCart(cart.map(x=>x.name===item.name?{...x,qty:x.qty+1}:x));else setCart([...cart,{...item,qty:1}])};const decreaseCart=(name)=>setCart(cart.map(x=>x.name===name?{...x,qty:x.qty-1}:x).filter(x=>x.qty>0));const removeFromCart=(name)=>setCart(cart.filter(x=>x.name!==name));const addMenu=()=>{if(!newMenu.name)return alert("ใส่ชื่อเมนูก่อน");setMenus([...menus,{...newMenu,image:newMenu.image||foodImages.thai}]);setNewMenu({category:"",name:"",price:"",desc:"",image:""})};
return <div className="app" style={{"--accent":site.accentColor,"--main":site.mainColor}}>
<button className="floatLine" onClick={()=>window.location.href=lineLink(cartText)}>LINE สั่งอาหาร</button>
<div className="mobileCart"><b>🛒 {totalQty} รายการ / {grandTotal} บาท</b><button onClick={()=>document.getElementById("cart")?.scrollIntoView({behavior:"smooth"})}>ดูตะกร้า</button></div>
<header><div><h1>{site.shopName}</h1><p>Boat Noodle • Khanom Jeen • Kaprao</p></div>{isAdminMode&&adminLoggedIn&&<Btn outline onClick={()=>setAdminLoggedIn(false)}>ออกจากแอดมิน</Btn>}</header>
{isAdminMode&&!adminLoggedIn&&<section className="login"><div><h2>เข้าสู่ระบบแอดมิน</h2><input type="password" placeholder="รหัสผ่านแอดมิน" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)}/><button onClick={()=>adminPassword==="1234"?setAdminLoggedIn(true):alert("รหัสผ่านไม่ถูกต้อง")}>เข้าหลังบ้าน</button><p>รหัสเริ่มต้น: 1234</p></div></section>}
{adminOpen&&<section className="admin"><h2>หลังบ้านแก้หน้าเว็บ</h2><div className="adminGrid">{[["shopName","ชื่อร้าน"],["headline","หัวข้อใหญ่"],["highlight","ข้อความไฮไลต์"],["slogan","สโลแกน"],["phone","เบอร์โทร"],["line","LINE"],["address","ที่อยู่"],["openTime","เวลาเปิด"],["deliveryFee","ค่าส่ง"],["bestseller1","เมนูขายดี 1"],["bestseller2","เมนูขายดี 2"],["bestseller3","เมนูขายดี 3"],["bestsellerCount","จำนวนขายแล้ว"],["review1","รีวิว 1"],["review2","รีวิว 2"],["review3","รีวิว 3"]].map(([k,l])=><label key={k}>{l}<input value={site[k]} onChange={e=>updateSite(k,e.target.value)}/></label>)}<label>สถานะร้าน<select value={site.shopStatus} onChange={e=>updateSite("shopStatus",e.target.value)}><option>เปิดอยู่</option><option>ปิดแล้ว</option><option>พักรับออเดอร์</option></select></label><label>สีหลัก<input type="color" value={site.mainColor} onChange={e=>updateSite("mainColor",e.target.value)}/></label><label>สีทอง<input type="color" value={site.accentColor} onChange={e=>updateSite("accentColor",e.target.value)}/></label><label className="wide">ข้อความแนะนำร้าน<textarea value={site.intro} onChange={e=>updateSite("intro",e.target.value)}/></label><label className="wide">ลิงก์แผนที่<input value={site.mapEmbedUrl} onChange={e=>updateSite("mapEmbedUrl",e.target.value)}/></label></div><div className="adminBlock"><b>รูปหน้าปก 3 รูป</b>{site.heroImages.map((img,i)=><input key={i} value={img} onChange={e=>{const n=[...site.heroImages];n[i]=e.target.value;updateSite("heroImages",n)}}/>)}</div><h3>เพิ่มเมนูใหม่</h3><div className="adminGrid"><input placeholder="หมวดหมู่" value={newMenu.category} onChange={e=>setNewMenu({...newMenu,category:e.target.value})}/><input placeholder="ชื่อเมนู" value={newMenu.name} onChange={e=>setNewMenu({...newMenu,name:e.target.value})}/><input placeholder="ราคา" value={newMenu.price} onChange={e=>setNewMenu({...newMenu,price:e.target.value})}/><input placeholder="ลิงก์รูป" value={newMenu.image} onChange={e=>setNewMenu({...newMenu,image:e.target.value})}/><button onClick={addMenu}>+ เพิ่มเมนู</button></div><h3>แก้เมนูอาหาร</h3><div className="catScroll">{categories.map(cat=><button key={cat} onClick={()=>setAdminCategory(cat)}>{cat}</button>)}</div><div className="editMenus">{adminMenus.map(({item,index})=><div key={index}><button onClick={()=>setMenus(menus.filter((_,i)=>i!==index))}>ลบ</button><input value={item.category} onChange={e=>updateMenu(index,"category",e.target.value)}/><input value={item.name} onChange={e=>updateMenu(index,"name",e.target.value)}/><input value={item.price} onChange={e=>updateMenu(index,"price",e.target.value)}/><textarea value={item.desc} onChange={e=>updateMenu(index,"desc",e.target.value)}/><input value={item.image} onChange={e=>updateMenu(index,"image",e.target.value)}/></div>)}</div></section>}
<section className="hero"><img className="heroBg" src={site.heroImages[0]}/><div className="heroContent"><div className="heroImages">{site.heroImages.map((img,i)=><img key={i} src={img}/>)}</div><div className="heroText"><div><span className="pill">✨ {site.slogan}</span><h2>{site.headline}<br/><em>{site.highlight}</em></h2><p>{site.intro}</p></div><div className="featureBox"><div>🍜<b>น้ำซุปเข้มข้น</b></div><div>🌿<b>วัตถุดิบสดใหม่</b></div><div>🔥<b>ผัดไฟแรง</b></div><div>{site.shopStatus==="เปิดอยู่"?"🟢":"🔴"}<b>{site.shopStatus}</b></div><div>⏰<b>เปิด {site.openTime}</b></div><div className="best"><p>เมนูขายดี</p>{[site.bestseller1,site.bestseller2,site.bestseller3].map(name=>{const item=menus.find(m=>m.name===name);return <Btn key={name} onClick={()=>item&&addToCart(item)} style={{background:site.accentColor,color:'#111',width:'100%',marginTop:8}}>+ สั่ง {name}</Btn>})}</div></div></div></div></section>
<section id="cart" className="cart"><h2>🛒 ตะกร้าสั่งอาหาร</h2>{cart.length===0?<p>ยังไม่มีสินค้าในตะกร้า</p>:cart.map(item=><div className="cartItem" key={item.name}><span>{item.name} x{item.qty}</span><div><button onClick={()=>decreaseCart(item.name)}>−</button><button onClick={()=>addToCart(item)}>+</button><button onClick={()=>removeFromCart(item.name)}>ลบ</button></div></div>)}<p>จำนวนรวม: {totalQty} รายการ<br/>ค่าอาหาร: {cartTotal} บาท<br/>ค่าจัดส่ง: {deliveryFee} บาท<br/><b>ยอดสุทธิ {grandTotal} บาท</b></p><div className="orderForm"><input placeholder="ชื่อผู้สั่ง" value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/><input placeholder="เบอร์โทร" value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/><select value={orderType} onChange={e=>setOrderType(e.target.value)}><option>รับเอง</option><option>จัดส่ง</option></select>{orderType==="จัดส่ง"&&<input placeholder="ที่อยู่จัดส่ง" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/>}<select value={customer.spicy} onChange={e=>setCustomer({...customer,spicy:e.target.value})}><option>ไม่เผ็ด</option><option>เผ็ดน้อย</option><option>เผ็ดกลาง</option><option>เผ็ดมาก</option></select><input placeholder="หมายเหตุ เช่น ไม่ใส่ผงชูรส / แยกน้ำ" value={customer.note} onChange={e=>setCustomer({...customer,note:e.target.value})}/></div><Btn onClick={()=>window.location.href=lineLink(cartText)} style={{background:'#06C755'}}>ส่งออเดอร์เข้า LINE</Btn> <span>LINE: {site.line}</span></section>
<section className="menus"><p>Signature Menu</p><h2>เมนูอาหารร้าน{site.shopName}</h2><div className="catScroll">{categories.map(cat=><button key={cat} onClick={()=>setSelectedCategory(cat)} className={selectedCategory===cat?'active':''}>{cat}</button>)}</div><div className="menuGrid">{visibleMenus.map((item,i)=><div className="card" key={item.name+i}>{bestsellerNames.includes(item.name)&&<><span className="badge">🔥 ขายดี</span><span className="sold">ขายแล้ว {site.bestsellerCount}</span></>}<img src={item.image} loading="lazy"/><div><small>{item.category}</small><h3>{item.name}</h3><p>{item.desc}</p><footer><b>{item.price}</b><Btn onClick={()=>addToCart(item)} style={{background:site.mainColor}}>+ ตะกร้า</Btn></footer></div></div>)}</div></section>
<section className="reviews"><p>Customer Reviews</p><h2>เสียงจากลูกค้า</h2><div>{[site.review1,site.review2,site.review3].map((r,i)=><article key={i}><b>★★★★★</b><p>“{r}”</p><small>— ลูกค้าบ้านอิ่มสุข</small></article>)}</div></section>
<section className="order"><div><p>Order Now</p><h2>สั่งอาหารร้าน{site.shopName}</h2><p>โทรสั่งอาหาร หรือเพิ่ม LINE ร้าน เพื่อสั่งล่วงหน้าได้ทันที</p></div><div><Btn style={{background:'white',color:'#111'}}>☎️ โทร: {site.phone}</Btn><Btn onClick={()=>window.location.href=lineLink(cartText)} style={{background:'#06C755'}}>LINE: {site.line}</Btn></div></section>
<section className="map"><h2>📍 แผนที่ร้าน</h2><iframe title="map" src={site.mapEmbedUrl} loading="lazy"></iframe><p>{site.address}</p><Btn onClick={()=>window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(site.address)}`,'_blank')} style={{background:site.accentColor,color:'#111'}}>เปิดใน Google Maps</Btn></section>
<footer>© ร้าน{site.shopName} — เว็บร้านอาหารพร้อมหลังบ้านแก้ไขได้</footer>
</div>}
createRoot(document.getElementById("root")).render(<App/>);
